# Stubs for gdb.printer.bound_registers (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

basestring = str
long = int

class MpxBound128Printer:
    val: Any = ...
    def __init__(self, val: Any) -> None: ...
    def to_string(self): ...
