# Stubs for gdb.function.as_string (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

import gdb
from typing import Any

class _AsString(gdb.Function):
    def __init__(self) -> None: ...
    def invoke(self, val: Any): ...
