# Stubs for gdb.function.in_scope (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

import gdb
from typing import Any

class InScope(gdb.Function):
    def __init__(self) -> None: ...
    def invoke(self, *vars: Any): ...
