# Stubs for gdb.command.ignore_errors (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

import gdb
from typing import Any

class IgnoreErrorsCommand(gdb.Command):
    def __init__(self) -> None: ...
    def invoke(self, arg: Any, from_tty: Any) -> None: ...
