# Stubs for gdb.backtrace (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

def push_frame_filter(constructor: Any): ...
def create_frame_filter(iter: Any): ...
